### ISSUE TITLE
android低版本ndk引入静态库编译失败

### ISSUE THREAD

**Issue by kllkko** [vintonliu/openssl-libs#1]
android-ndk-r14b

E:/work.../jni/prebuilt/lib/libcrypto.a(cryptlib.o):cryptlib.c:function OPENSSL_showfatal: error: undefined reference to 'stderr'
E:/work.../jni/prebuilt/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function close_console: error: undefined reference to 'stdin'
E:/work.../jni/prebuilt/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function close_console: error: undefined reference to 'stderr'
E:/work.../jni/prebuilt/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'signal'
E:/work.../jni/prebuilt/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
E:/work.../jni/prebuilt/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
E:/work.../jni/prebuilt/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function open_console: error: undefined reference to 'tcgetattr'
E:/work.../jni/prebuilt/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function open_console: error: undefined reference to 'stdin'
E:/work.../jni/prebuilt/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function open_console: error: undefined reference to 'stderr'
E:/work.../jni/prebuilt/lib/libcrypto.a(eng_openssl.o):eng_openssl.c:function openssl_load_privkey: error: undefined reference to 'stderr'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by wenchang85** [comment]
是的，我编译的时候 API 设置的是 23，你编译的时候也要相应设置 API 为 23 才编译的过

**Comment by wenchang85** [comment]
或者可以 从 https://gitee.com/vintonliu/openssl.git  clone 下来，并切换到OpenSSL_1_1_1d_build分支，使用 build_android.sh 脚本自行编译
